apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
spec:
  template:
    spec:
      containers:
      - name: service-a
        image: quay-registry-quay-quay-registry.apps.ocp4.example.com/user1/service-a
